### ISSUE TITLE
How to hook an enum?

### ISSUE THREAD

**Issue by ghost** [kotori2/riru_unity_example#10]
Hi, I have a problem hooking a enum; here is the enum to hook:
![image](https://user-images.githubusercontent.com/98092901/172820744-9401c336-847c-417d-8950-39f3a552fbf5.png)

And this is the method which use it:
![image](https://user-images.githubusercontent.com/98092901/172821384-1fd1fde3-e638-4347-b91e-052f2691b5b8.png)

And this is the code to hook it:
![image](https://user-images.githubusercontent.com/98092901/172820836-c71f0f6e-7655-45d6-af57-e9bf6a30428c.png)

Is this correct? Because my game crash when loading this hook.

**Comment by kotori2** [comment]
Integer constants like enums will 100% inlined by compiler, so it's not possible to hook an enum.

**Comment by ghost** [comment]
I solved it. Just include KittyMemory and patch it manually.
![image](https://user-images.githubusercontent.com/98092901/172832318-3b625867-e8ed-4b91-85a4-9d49ffa132b0.png)

**Comment by ghost** [comment]
Well, for some reason now it doesn't work. When I try to hook the function which return the enum the game crash. Also I tried with KittyMemory and still doesn't work. Is it possible to hook the return of a function which is an enum? In KittyMemory I patched like an Integer.

**Comment by kotori2** [comment]
Yes you should hook the function and return an integer. 
Personally I will use Dobby as shown in the example files. 
You might gonna check stacktrace from adb.

**Comment by kotori2** [comment]
My best guess is, it is a super simple function, so it must be inlined during compiling. So you might gonna figure out who called `get_SkipMode`. But I have no idea why it crash.

**Comment by ghost** [comment]
Thanks for the help but I have finally managed to get it to work. I just hooked the LateUpdate() function and with Ghidra decompiled the lib to know the offset.
![image](https://user-images.githubusercontent.com/98092901/199826799-05980452-deab-44dc-b8b7-f2da8ef933e1.png)
![image](https://user-images.githubusercontent.com/98092901/199826823-6af8698b-3df1-4238-b0ad-d904b76d4134.png)
