### ISSUE TITLE
Riru能够读写SD卡么?

### ISSUE THREAD

**Issue by yhnu** [kotori2/riru_unity_example#3]
最近刚接触Riru,发现不能读写SD卡里面的问题. 能否请教下呢?

**Comment by kotori2** [comment]
Riru是注入应用的，如果应用没有sd卡权限的话Riru也没有

**Comment by yhnu** [comment]
我给应用给了权限但是还是没发写如sd卡.大概是个什么情况呢?

![image](https://user-images.githubusercontent.com/23090916/81496493-918a8b80-92ea-11ea-8cba-23fc669d4b92.png)
![image](https://user-images.githubusercontent.com/23090916/81496499-9cddb700-92ea-11ea-851c-aaca1c2a3be9.png)

**Comment by kotori2** [comment]
@yhnu no idea. 我只知道第一个error 2大概是因为你没创建文件夹，后面那俩不行的话可以试试/data/emulated/0
另外是不是方向错了？为什么要往sdcard里写东西，直接logcat不好么（

**Comment by yhnu** [comment]
@kotori2 1. 第一个文件是存在的,但是不知道为啥报那个错误  2.主要是想记录一些内存数据,方便做数据分析.

**Comment by yhnu** [comment]
hi, kotori2:
能给个联系方式么?遇到问题了大家一起交流交流
