### ISSUE TITLE
how to get char array value from std::string 

### ISSUE THREAD

**Issue by ghost** [kotori2/riru_unity_example#4]
I have hooked a function,which takes one filename param of string type, how do I print out the string char array value of it ?
this is on android arm .
void (*setbackgroundimage)(void *lay, const std::string& fileName, int);

**Comment by kotori2** [comment]
use `cSharpString* fileName` as param, and print `fileName->buf`
data in Il2cpp world is not using STL class

**Comment by ghost** [comment]
is this cSharpString struct got from ida ?

**Comment by kotori2** [comment]
No. That's from memory dump.

oxpy <notifications@github.com> 于 2020年5月27日周三 21:25写道：

**Comment by ghost** [comment]
May I ask how did you dump it from memory ?  what tools are used ?
gdb ? ida script ?

**Comment by kotori2** [comment]
bRuH, you already injected into the game, what can stop you from dumping memory?
e.g.: 
```
char* ptr = 0x7f1234abcd;
for(int i=0; i < 16; i++) LOGI("dump: %c", *(ptr+i));  
```
