### ISSUE TITLE
这个项目是在whale框架基础上面开发出来的么

### ISSUE THREAD

**Issue by ghost** [kotori2/riru_unity_example#6]

**Comment by kotori2** [comment]
No. Whale is for inline hooking only

oxpy <notifications@github.com> 于 2020年5月28日周四 16:47写道：

**Comment by ghost** [comment]
so what is the difference for this project?

**Comment by kotori2** [comment]
Of course you can do your draft from whale. But you have to handle ELF handle stuffs yourself.

**Comment by ghost** [comment]
Is the code files under whale directory a new hook framework?
