### ISSUE TITLE
__loader_dlopen returns 0

### ISSUE THREAD

**Issue by mohdali** [kotori2/riru_unity_example#8]
Hi,

I'm trying your template on an Android Marshmallow Phone (6.0.1).

However, I see that the below call

`void* __loader_dlopen = dlsym(dl, "__loader_dlopen");`

returns 0. Which makes the rest of the code fail.

Can you please point me if I need to used a different call in Marshmallow?

**Comment by mohdali** [comment]
Ok, found my answer,

I could just hook to dlopen itself.

The code wrok likea charm now. Thanks! It saved me a lot of time.

**Comment by kotori2** [comment]
Actually it is way more easier for you to get soinfo in Android 6.0 using do_dlopen.

**Comment by mohdali** [comment]
Yes. In android 6 it is easier. Thanks a lot.
