### ISSUE TITLE
Symbol name pattern of do_dlopen

### ISSUE THREAD

**Issue by vilebbit** [kotori2/riru_unity_example#9]
Hello, 
I have successfully hooked some certain games using your illustrious repo, they all work like a charm, you have my many thanks! 
As a consequence, I decided to dig into it deeper to find out how it works and have understood most of them except one point: 
https://github.com/kotori2/riru_unity_example/blob/d8ca40cd6feb6dfd81120b8346d106492f3a2eff/module/src/main/cpp/hook_main.cpp#L134

What confuses me is, where did you get this symbol name pattern exactly? 
I have looked into `libdl.so` as well as searching a bunch of references but got nothing at the end. 
I wonder if you don't mind giving me a hint, thanks.

**Comment by kotori2** [comment]
https://cs.android.com/android/platform/superproject/+/master:bionic/linker/linker.cpp;l=2063?q=do_dlopen
in `linker`

**Comment by vilebbit** [comment]
That exactly is it. But where do those weird suffix and prefixes come from?

**Comment by kotori2** [comment]
> That exactly is it. But where do those weird suffix and prefixes come from?

https://en.wikipedia.org/wiki/Name_mangling

**Comment by kotori2** [comment]
我超 我是不是上个月看过你博客（x

**Comment by vilebbit** [comment]
草，大佬为什么会看我的博客（

> > That exactly is it. But where do those weird suffix and prefixes come from?
> 
> https://en.wikipedia.org/wiki/Name_mangling

我一开始也想到会不会是编译的时候有混淆，所以试着把`libdl.so`反编译出来看了下，然而发现里面的符号是纯净的。

**Comment by vilebbit** [comment]
啊我明白了，在`bin/linker64`里面

**Comment by kotori2** [comment]
> 我一开始也想到会不会是编译的时候有混淆

只是因为C++的符号导出的时候需要一个类似转义的操作而已啦……

> 草，大佬为什么会看我的博客（

之前拆IP来着（

**Comment by vilebbit** [comment]
撞上盲点了，光想着动态链接库，忘了还有可执行文件（ 
问题解决，感谢！
